# Form implementation generated from reading ui file '.\ui\auth.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_login = QtWidgets.QLabel(parent=Form)
        self.label_login.setObjectName("label_login")
        self.verticalLayout.addWidget(self.label_login)
        self.lineEdit_login = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.verticalLayout.addWidget(self.lineEdit_login, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_pass = QtWidgets.QLabel(parent=Form)
        self.label_pass.setObjectName("label_pass")
        self.verticalLayout.addWidget(self.label_pass)
        self.lineEdit_pass = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.verticalLayout.addWidget(self.lineEdit_pass, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_user = QtWidgets.QPushButton(parent=Form)
        self.pushButton_user.setObjectName("pushButton_user")
        self.horizontalLayout.addWidget(self.pushButton_user)
        self.pushButton_guest = QtWidgets.QPushButton(parent=Form)
        self.pushButton_guest.setObjectName("pushButton_guest")
        self.horizontalLayout.addWidget(self.pushButton_guest)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Авторизация"))
        self.label.setText(_translate("Form", "Авторизация"))
        self.label_login.setText(_translate("Form", "Логин"))
        self.lineEdit_login.setPlaceholderText(_translate("Form", "Ввод логина"))
        self.label_pass.setText(_translate("Form", "Пароль"))
        self.lineEdit_pass.setPlaceholderText(_translate("Form", "Ввод пароля"))
        self.pushButton_user.setText(_translate("Form", "Войти"))
        self.pushButton_guest.setText(_translate("Form", "Войти как гость "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
