# Form implementation generated from reading ui file '.\ui\card.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(712, 183)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_image = QtWidgets.QLabel(parent=Form)
        self.label_image.setMaximumSize(QtCore.QSize(300, 200))
        self.label_image.setObjectName("label_image")
        self.horizontalLayout.addWidget(self.label_image)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_name = QtWidgets.QLabel(parent=Form)
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_brand = QtWidgets.QLabel(parent=Form)
        self.label_brand.setObjectName("label_brand")
        self.verticalLayout.addWidget(self.label_brand, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_price = QtWidgets.QLabel(parent=Form)
        self.label_price.setObjectName("label_price")
        self.verticalLayout.addWidget(self.label_price, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_image.setText(_translate("Form", "TextLabel"))
        self.label_name.setText(_translate("Form", "TextLabel"))
        self.label_brand.setText(_translate("Form", "TextLabel"))
        self.label_price.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
